In [ ]:
# loops
#while
# for

In [ ]:
a = 0
while(a < 10):
  print(a)
  a = a+1
#a++ not possible
#true (infinte loop)

0
1
2
3
4
5
6
7
8
9


In [ ]:
i = 1
n = 2
while( i <= 10):
  print(n,"'",i,"'",n*i)
  i=i+1

2 ' 1 ' 2
2 ' 2 ' 4
2 ' 3 ' 6
2 ' 4 ' 8
2 ' 5 ' 10
2 ' 6 ' 12
2 ' 7 ' 14
2 ' 8 ' 16
2 ' 9 ' 18
2 ' 10 ' 20


In [ ]:
#break() - terminates the loop and resumes execute the next stmt
#and continue()
 
a =10 
while(a > 0):
  print(a)
  a = a-1
  if a == 5:
    break #if a value reaches then it does not repeat
print("hello")



10
9
8
7
6
hello


In [ ]:
#continue()- returns the control to the beginning of the loop and continue the other stmt
b = 10
while b > 0:
  b = b-1
  if b == 5: #excepr 5 all others are available
    continue
  print("current value of b",b)
print("hello")

current value of b 9
current value of b 8
current value of b 7
current value of b 6
current value of b 4
current value of b 3
current value of b 2
current value of b 1
current value of b 0
hello


In [ ]:
b = 10
while b > 0:
  b = b-1
  
    
  print("current value of b",b)
print("hello")

current value of b 9
current value of b 8
current value of b 7
current value of b 6
current value of b 5
current value of b 4
current value of b 3
current value of b 2
current value of b 1
current value of b 0
hello


In [ ]:
#pass() is used when a stmt is required but u dont want any command or  code to execute it
while True:
  print("a")
  pass

In [ ]:
#*
#* *
#* * *
i= 0
while(i <= 4):
  print(i*"*")
  i = i+1


*
**
***
****


In [ ]:
#nested while loops
n = int(input("enter the no of times"))
 
i = 1
while i <= n :
  j = 1
  while j <= i:
    print("*",end="")
    j = j+1

  print()
  i = i+1




enter the no of times3
*
**
***


In [ ]:
#for

In [ ]:
for i in range(10):
  print(i) 

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(3,10):
  print(i)

3
4
5
6
7
8
9


In [ ]:
for i in range(5,20,3):#(star,end,increment/decrement)
  print(i)

5
8
11
14
17


In [ ]:
for i in range(5,20,3):
  print(i,end = " ")

5 8 11 14 17 

In [ ]:
for i in range(20,10,2):
  print(i)#blank answer since not ossible

In [ ]:
for i in [1,2,3,4,5,6]:
  print(i)

1
2
3
4
5
6


In [ ]:
n = 2
for i in range(1,10):
  print(f'{n} *{i} = {n*i}')

2 *1 = 2
2 *2 = 4
2 *3 = 6
2 *4 = 8
2 *5 = 10
2 *6 = 12
2 *7 = 14
2 *8 = 16
2 *9 = 18


In [ ]:
import time
for i in range(1,10):
  print(i)
  time.sleep(2)

1
2
3
4
5
6
7
8
9


In [ ]:
import time
prices = [10,20,30,40]
result =0
for i in prices:
  result = result +i
  print(result)
  time.sleep(1)
print(f'end of result,RESULT={result}')

10
30
60
100
end of result,RESULT=100


In [ ]:
#two dice probability
for x in range(4):
  for y in range(3):
    print(f'{x},{y}')

0,0
0,1
0,2
1,0
1,1
1,2
2,0
2,1
2,2
3,0
3,1
3,2


In [ ]:
import time
seconds =time.time()
local_time = time.ctime(seconds)
print(local_time)

Tue Jan  4 15:47:00 2022


In [ ]:
 from random import randint
print(randint(0,10))

5


In [ ]:
from random import randint
print(randint(0,9),randint(0,9),randint(0,9))
# OTP 

3 8 9


In [ ]:
#numpy -numerical pythom
import numpy
print(numpy.random.randint(0,9,20))

[5 7 1 0 6 1 4 0 3 0 0 7 1 1 3 3 2 7 5 6]


In [ ]:
import random
import string
random.choice(string.ascii_letters)


'h'

In [ ]:
print(random.choice(string.ascii_letters),(string.ascii_letters))

b abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ


In [ ]:
#FUNCTIONS
#block ofcode which runs when we call it
def my_function(): #fuction definition
  print("hello")


In [ ]:
my_function() #fuction call

hello


In [ ]:
def ask_name():
  name=input("enter your name:")
  print("your name is :",name)
ask_name()

enter your name:norah
your name is : norah


In [ ]:
def function12(name):
  print("hello",name)
  print("how do you do ?")

function12("norah")

hello norah
how do you do ?


In [ ]:
a = "first"
b = "first"
print(id(a))

print(id(b))

140100480129264
140100480129264


In [ ]:
def add(n1,n2): #n1n2 parametes
   result = n1+n2 print("resut:",result)

add(3,2)

In [ ]:
function12(" norah")
add(1,2)

hello  norah
how do you do ?
resut: 3


In [ ]:
def ask_yes_no(prompt):
  while True:
    answer = input(prompt ='(y or n)')
    if answer == 'y' or answer =='Y':
      return True
    if answer == 'N ' or 'N':
      return False
    print("answer Y or N")
# print y or no
if ask_yes_no("do you like pizza?"):
    print("you like pizza")
else:
    print("you dont like pizza")

(y or n)y
you like pizza


In [ ]:
#NUMPY
#library support for high level maths
#eg:array, fourier and all


In [ ]:
import numpy as np
#arrays

In [ ]:
arr = np.array(42)
print(arr)

42


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

0

In [ ]:
# 0 dimension
arr = np.array(42) #o dimensional numpy array
print(arr)

#1 dimensiom
arr1 = np.array([1,5,6,7,])
print(arr1)
#2 dimension
arr2=np.array([[1,2,3,4],[7,2,9,10]])
print(arr2)

#higher dimensiom
arr_high = np.array([1,2,3,4,5,6,7],ndmin=6)
print(arr_high)

42
[1 5 6 7]
[[ 1  2  3  4]
 [ 7  2  9 10]]
[[[[[[1 2 3 4 5 6 7]]]]]]


In [ ]:
arr2.ndim

2

In [ ]:
arr_high.ndim

6

In [ ]:
arr1

array([1, 5, 6, 7])

In [ ]:
a = np.array([1,"a",3])
type(a)

numpy.ndarray

In [ ]:
a
#u21 ,u16 are unicode

array(['1', 'a', '3'], dtype='<U21')

In [ ]:
a.dtype

dtype('<U21')

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr_high.dtype

dtype('int64')

In [ ]:
text_array = np.array(["aaaa",'bbbbb'])
text_array

array(['aaaa', 'bbbbb'], dtype='<U5')